### ISSUE TITLE
Logging Setup Snags

### ISSUE THREAD

**Issue by jbaldo** [ekkus93/councilmatic-docker#1]
Logging bumps I hit while setting up docker container

**Comment by jbaldo** [comment]
```
The path /usr/local/var/postgres
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

**Comment by jbaldo** [comment]
If I `initdb opencivicdata`, set my postgres data dir to that dir in `docker-compose.yml` and then `docker-compose up`, I get:
```bash
postgres_1  | FATAL:  "/var/lib/postgresql/data" is not a valid data directory
postgres_1  | DETAIL:  File "/var/lib/postgresql/data/PG_VERSION" does not contain valid data.
postgres_1  | HINT:  You might need to initdb.
```

If I delete the `opencivicdata` folder and run... it seems to do some stuff?

**Comment by jbaldo** [comment]
`docker exec -it -u postgres 94cd587047a0 bash`

one dash for the `it` flag rather than two

**Comment by jbaldo** [comment]
after `cd /home/postgres/councilmatic/work`

```bash
bash: cd: /home/postgres/councilmatic/work: No such file or directory
```

**Comment by jbaldo** [comment]
When running `pupa update oakland`:
```python
(councilmatic) postgres@94cd587047a0:~/work$ pupa update oakland
no pupa_settings on path, using defaults
Traceback (most recent call last):
  File "/home/postgres/councilmatic/bin/pupa", line 11, in <module>
    load_entry_point('pupa==0.8.0.dev0', 'console_scripts', 'pupa')()
  File "/home/postgres/councilmatic/lib/python3.4/site-packages/pupa/cli/__main__.py", line 67, in main
    subcommands[args.subcommand].handle(args, other)
  File "/home/postgres/councilmatic/lib/python3.4/site-packages/pupa/cli/commands/update.py", line 251, in handle
    juris, module = self.get_jurisdiction(args.module)
  File "/home/postgres/councilmatic/lib/python3.4/site-packages/pupa/cli/commands/update.py", line 139, in get_jurisdiction
    module = importlib.import_module(module_name)
  File "/home/postgres/councilmatic/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'oakland'
```

This because it's not finding some settings (I see `no pupa_settings on path, using defaults`) or...

**Comment by jbaldo** [comment]
nevermind, `pupa dbinit us` failed during setup. I think that was the problem

**Comment by jbaldo** [comment]
Nope, didn't work. Found this: http://opencivicdata.readthedocs.io/en/latest/scrape/run_scraper.html

So is it looking for an `oakland` directory somewhere? will dig through file directory...

**Comment by jbaldo** [comment]
Ohh, I get it. I think I need this repo in conjunction with yours?
https://github.com/openoakland/councilmatic-scraper

**Comment by jbaldo** [comment]
Thanks, @ekkus93. Sorry, I didn't mean this as a complaint. Just stream of consciousness logging that I'm now realizing might have generated a lot of emails for you. Sorry about that. Planned to submit a PR to update the README but you beat me to it!

**Comment by ekkus93** [comment]
I updated the readme.  It should be ok now. Thanks.
